MEGABYTE = 2**20
GIGABYTE = 2**30

DATABASE_PATH = "/home/jdp/neo4j/data"
MAX_DATABASE_SIZE = MEGABYTE*5

SETTINGS = {
    'DATABASE_PATH' : DATABASE_PATH,
    'MAX_DATABASE_SIZE' : MAX_DATABASE_SIZE
}
